version = 0.1
[default.deploy.parameters]
stack_name = "backend-aiit-campus-voice"
resolve_s3 = true
s3_prefix = "backend-aiit-campus-voice"
region = "ap-northeast-1"
profile = "mini-pbl"
capabilities = "CAPABILITY_IAM"
image_repositories = []
