AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  backend-aiit-campus-voice

  Sample SAM Template for backend-aiit-campus-voice

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  # Function単位でLambda関数を定義する.
  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.controller.health_handler # app/controller#health_handlerメソッド
      Runtime: python3.9
      CodeUri: .
      Events:
        TopApi:
          Type: Api
          Properties:
            Path: /health 
            Method: GET
  TopApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.controller.top_handler # app/controller#top_handlerメソッド
      Runtime: python3.9
      CodeUri: .
      Events:
        TopApi:
          Type: Api
          Properties:
            Path: /top
            Method: GET
Outputs:
  # API Gatewayのエンドポイントを出力
  HealthApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/health/"
  # Lambda関数のAmazon Resouce Nameを出力
  HealthFunction:
    Description: "HealthLambda Function ARN"
    Value: !GetAtt HealthFunction.Arn
  # Lambda関数に関連付けられたIAMロールのARNを出力
  HealthFunctionIamRole:
    Description: "Implicit IAM Role created for Health function"
    Value: !GetAtt HealthFunctionRole.Arn

  TopApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/top/"
  TopFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt TopFunction.Arn
  TopFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt TopFunctionRole.Arn
